### ISSUE TITLE
Nothing published

### ISSUE THREAD

**Issue by Wheemer** [maweki/ncid-mqtt-relay#2]
Hello;

I am trying to get your code up and working but I never see it publish anything. I have the setting correct I have triple checked it.

Is that perhaps a recent change that may have broken this?

Thanks for you help.

Steve

**Comment by maweki** [comment]
I am no longer using this myself. But have you got the ncid server running correctly? Can you connect to it (via telnet, for example) and does it show the correct output? Do you get any exceptions or error messages?

**Comment by Wheemer** [comment]
Hello;

Yes it connects to ncid running fine locally on debian. When I run the script from prompt it shows all the CID CIDLOG etc.

The problem is it is not publishing to mqtt. I am running home assistant supervised so the mqtt is ha docker addon.

**Comment by maweki** [comment]
I would suggest trying to connect to your mqtt server using paho within an interactive python session and see what works.

Maybe there's something else, like ssl encryption that I haven't tried myself. I only needed user, password, and port. Maybe you need something else.

Is your server configured in a way that you need to create the topics beforehand or are new topics just picked up? Maybe that's the issue.

**Comment by Wheemer** [comment]
I am just using the standard mosquito broker addon in home assistant.

I just tested with this script

`import paho.mqtt.client as mqtt #import the client1
broker_address="192.168.1.40"
client = mqtt.Client("P1") #create new instance
client.username_pw_set(username="mqtt", password="XXXXXXX")
client.connect(broker_address) #connect to broker
client.publish("house/main-light","OFF")#publish`

And it published right away.

Is it perhaps something with the timestamps, it there a way to make it print everything? I am a newbie to this so forgive me if I'm way off base.

**Comment by Wheemer** [comment]
In my endless testing I have done these two things, maybe there are more prerequisites?

pip install datetime
pip install regex

Was this correct?

**Comment by maweki** [comment]
> Was this correct?

No, sadly not. There are no other dependencies besides `paho`. Everything else is an internal python module.

> is there a way to make it print everything?

You already get most of the useful output.

https://github.com/maweki/ncid-mqtt-relay/blob/master/ncid-relay.py#L73

Do you get the "connected" message?

It should also print everything it reads from the mqtt server:

https://github.com/maweki/ncid-mqtt-relay/blob/master/ncid-relay.py#L76

Do you get any output?

**Comment by maweki** [comment]
Do you have the relay on the same computer as the ncidd server? Is there maybe a firewall blocking access to ncidd?

**Comment by Wheemer** [comment]
There is one connected on the very first log line.

Here's a log snippet from the most recent:

`CIDLOG: *DATE*11152023*TIME*1516*LINE*VOIP*NMBR*709215XXXX*MESG*NONE*FNMBR*(709) 215-XXXX*NTYPE*FIX/CELL*CTRY*CA*LOCA*Newfoundland and Labrador*CARI*TELUS Mobility*NAME*709215XXXX*
250 End of call log 1700073990
OPT: country: CA
OPT: LineIDs: "VOIP"
OPT: hangup-1
OPT: hupmode-1
OPT: ignore1
OPT: regex-0
300 End of connection startup
CIDINFO: *LINE*VOIP*RING*4*TIME*15:16:47*
CIDINFO: *LINE*VOIP*RING*5*TIME*15:16:53*
CIDINFO: *LINE*VOIP*RING*0*TIME*15:17:02*
CIDINFO: *LINE*VOIP*RING*1*TIME*18:58:58*
CID: *DATE*11152023*TIME*1858*LINE*VOIP*NMBR*709708XXXX*MESG*NONE*FNMBR*(709) 708-XXXX*NTYPE*FIX/CELL*CTRY*CA*LOCA*Newfoundland and Labrador*CARI*Iristel Inc.*NAME*709708XXXX*
CIDINFO: *LINE*VOIP*RING*2*TIME*18:59:04*
CIDINFO: *LINE*VOIP*RING*3*TIME*18:59:10*
CIDINFO: *LINE*VOIP*RING*0*TIME*18:59:19*
CIDINFO: *LINE*VOIP*RING*1*TIME*19:15:35*
CID: *DATE*11152023*TIME*1915*LINE*VOIP*NMBR*709215XXXX*MESG*NONE*FNMBR*(709) 215-XXXX*NTYPE*FIX/CELL*CTRY*CA*LOCA*Newfoundland and Labrador*CARI*TELUS Mobility*NAME*709215XXXX*
CIDINFO: *LINE*VOIP*RING*2*TIME*19:15:41*
CIDINFO: *LINE*VOIP*RING*3*TIME*19:15:47*
CIDINFO: *LINE*VOIP*RING*0*TIME*19:15:56*`

And yes they are both on the same machine.

**Comment by maweki** [comment]
I see your issue. Your CID-Line doesn't conform to the one I wrote. I'll have fix for you in a few hours, as it is a bit more involved.

**Comment by Wheemer** [comment]
Hello;

I am so happy that you see an issue. Is it a setting in NCID I may need to change? I did change the phone number formatting in NCID conf.

Is there any way to pull all the info provided into mqtt?

**Comment by maweki** [comment]
try the new version. It now takes arbitrary CID/PID lines. Though I haven't tested it.

**Comment by Wheemer** [comment]
OK, I have it in place. But unfortunately I cannot test as I have people still sleeping in the house for probably 6-7 more hours.

I can only hope someone else calls, lol.

I will update you when I have feedback.

Thank you so much for your help and attention.

**Comment by Wheemer** [comment]
OK I just tested it without cause an actual ring

CIDINFO: *LINE*VOIP*RING*1*TIME*06:44:24*
CID: *DATE*11162023*TIME*0644*LINE*VOIP*NMBR*647947XXXX*MESG*NONE*FNMBR*(647) 947-XXXX*NTYPE*FIX/CELL*CTRY*CA*LOCA*Ontario*CARI*Fibernetics Corporation*NAME*REIDS GARAGE*
call DATE*11162023*TIME*0644*LINE*VOIP*NMBR*647947XXXX*MESG*NONE*FNMBR*(647) 947-XXXX*NTYPE*FIX/CELL*CTRY*CA*LOCA*Ontario*CARI*Fibernetics Corporation*NAME*REIDS GARAGE
{'DATE': '11162023', 'TIME': '0644', 'LINE': 'VOIP', 'NMBR': '647947XXXX', 'MESG': 'NONE', 'FNMBR': '(647) 947-XXXX', 'NTYPE': 'FIX/CELL', 'CTRY': 'CA', 'LOCA': 'Ontario', 'CARI': 'Fibernetics Corporation', 'NAME': 'REIDS GARAGE', 'datetime': datetime.datetime(2023, 11, 16, 6, 44)}
Traceback (most recent call last):
  File "/opt/ncid-mqtt-relay/ncid-relay.py", line 73, in <module>
    main(args.ncid_server, args.mqtt_server, args.mqtt_topic, args.mqtt_auth)
  File "/opt/ncid-mqtt-relay/ncid-relay.py", line 66, in main
    raise E
  File "/opt/ncid-mqtt-relay/ncid-relay.py", line 64, in main
    incoming_call(client, mqtt_topic, match.group(1))
  File "/opt/ncid-mqtt-relay/ncid-relay.py", line 37, in incoming_call
    client.publish(topic, json.dumps(data))
                          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable

**Comment by Wheemer** [comment]
I just realized ncid has a plugin for voip that may get more information. If I changed to that would it affect this script?

Ultimately I am looking for hook status and the clearest info.

**Comment by maweki** [comment]
>  TypeError: Object of type datetime is not JSON serializable

Remove this line:
https://github.com/maweki/ncid-mqtt-relay/blob/master/ncid-relay.py#L32

> If I changed to that would it affect this script?

No, it should not. It only reacts to PID/CID lines and ignores all the rest.

> Ultimately I am looking for hook status and the clearest info.

I am not sure you get hook status from ncid. I always thought it was just incoming/ring. But if you show me a line from ncid, I can include that pattern.

**Comment by Wheemer** [comment]
Hello;

OK I got a published line, but I think since it's no longer formatted the sensor in HA always says no active call.

I'm waiting on the sip integration since that is not important or working yet.

I edited the sensor to reflect the change and it is working!

I am going to play with the sensor now to perfect it.

Thanks again so much man, I really appreciate all your help.

**Comment by Wheemer** [comment]
I may be bugging you too much, if I am please let me know.

I was wondering how hard it would be to have a ringing or idle sensor, I guess it should turn on with ring 1 and off with ring 0.

My mother is hard of hearing and I used to use the modem integrations feature like this to have lights flash to help her to know the phone is ringing.

**Comment by maweki** [comment]
> I was wondering how hard it would be to have a ringing or idle sensor

So what you want is to react to cidinfo as well. No problem at all. I just added that. It gets published to the same topic though. But I think you can probably get going from there.

https://github.com/maweki/ncid-mqtt-relay/commit/0fed6f6a14183bebaf8c7bbe824c876f8734bbb9

**Comment by Wheemer** [comment]
That sounds awesome... I can parse it out with different sensors in HA.

So I still have to remove "data['datetime'] = d"?

**Comment by maweki** [comment]
> So I still have to remove "data['datetime'] = d"?

yeah, sorry. I'll remove that myself

> I guess it should turn on with ring 1 and off with ring 0.

You should make a ring-sensor (template sensor) that shows the latest ring-value and then you should make a template-binary-sensor that is just off when the ring-sensor is equal to 0 and on otherwise.

**Comment by Wheemer** [comment]
This is working really well already.

Yeah I am going to have to fool around for a while to figure it all out. Thanks for the pointers.

It is disappointing that hook status is not reported... that's the only thing left. I am going to still investigate the sip2ncid after I get this all figured out.

**Comment by maweki** [comment]
> Yeah I am going to have to fool around for a while to figure it all out. Thanks for the pointers.

Good luck with that.

Please post an update in this thread what you ultimately did end up doing, as a pointer for other people stumbling around this space.

**Comment by Wheemer** [comment]
I will for sure.

Have a fantastic day, and thanks so much for your help.

Steve

**Comment by Wheemer** [comment]
OK I changed your script to split the two into different sensors:

`#!/usr/bin/python3
#-*-coding: utf-8-*-

import socket
import re
import paho.mqtt.client as mqtt
import json
import datetime
#from itertools import batched # python3.12

def parse_optional(ip_string, default_port, cast=(lambda x: x)):
    ip, _, port = ip_string.partition(':')
    port = port or default_port
    return ip, cast(port)

def parse_args():
    import argparse
    parser = argparse.ArgumentParser(description='Relay ncid data to mqtt server.')
    parser.add_argument('ncid_server')
    parser.add_argument('mqtt_server')
    parser.add_argument('mqtt_topic')
    parser.add_argument('mqtt_topic2')
    parser.add_argument('--mqtt_auth', type=str, default=None)
    return parser.parse_args()

def incoming_call(client, topic, incoming_string):
    print("call", incoming_string)
    data_array = incoming_string.split("*")
    # data = dict(batched(data_array, 2)) # This only works in python3.12
    data = dict(zip(data_array[::2],data_array[1::2]))
    d = datetime.datetime(int(data["DATE"][4:8]), int(data["DATE"][0:2]), int(data["DATE"][2:4]),
                        int(data["TIME"][0:2]), int(data["TIME"][2:4]))
    now = datetime.datetime.now()
    print(data)
    delta = abs(now - d)
    if delta.seconds < 300:
        client.publish(topic, json.dumps(data))
        print("published")
    else:
        print("delta too large")

def info(client, topic, info_string):
    print("info", info_string)
    data_array = info_string.split("*")
    data = dict(zip(data_array[::2],data_array[1::2]))
    client.publish(topic, json.dumps(data))
    print("published")

incoming_regex = re.compile(r'^[PC]ID: \*(.*)\*$')
info_regex = re.compile(r'^[PC]IDINFO: \*(.*)\*$')
def main(ncid_server, mqtt_server, mqtt_topic, mqtt_topic2, mqtt_auth):
    ncid_host, ncid_port = parse_optional(ncid_server, 3333, int)
    mqtt_host, mqtt_port = parse_optional(mqtt_server, 1883, int)

    while True:
        client = mqtt.Client()
        if mqtt_auth:
            mqtt_username, mqtt_password = parse_optional(mqtt_auth, None)
            client.username_pw_set(mqtt_username, mqtt_password)
        client.connect(mqtt_host,
                       mqtt_port,
                       60)
        client.loop_start()
        s = socket.socket()
        try:
            s.connect((ncid_host, ncid_port))
            print("connected")
            while True:
                data = s.recv(1024).decode().strip()
                print(data)
                if (match := incoming_regex.match(data)):
                  incoming_call(client, mqtt_topic, match.group(1))
                if (match := info_regex.match(data)):
                  info(client, mqtt_topic2, match.group(1))
        except Exception as E:
            raise E
        finally:
            s.close()
            client.disconnect()

if __name__ == "__main__":
    args = parse_args()
    main(args.ncid_server, args.mqtt_server, args.mqtt_topic, args.mqtt_topic2, args.mqtt_auth)
`


And here are the two sensors in HA config:

mqtt:
  sensor:
  - name: "Ring"
    unique_id: "ringdetect"
    state_topic: "Phone/info"
    value_template: "{% if value_json.RING %} Ring {{ value_json.RING }} {% else %} No active call {% endif %}"

text:
  - name: "Caller ID"
    unique_id: "caller_id"
    mode: "text"
    value_template: "{% if value_json.NAME %} {{ value_json.NAME }} at {{ value_json.FNMBR }} in {{ value_json.LOCA }},{{ value_json.CTRY }} {% endif %}"
    command_topic: "Phone/callerid"
    state_topic: "Phone/callerid"
